### Data Generation

- Each CSV file contains a snapshot at a given time of a speed of a list of boats
- Pandas is used to generate the files.
- In this first example, we follow 20 boats for 10 time steps.
- Each time step corresponds to a file
- Cell #1 creates the initial snapshot, Cell #2 makes it evolve

In [1]:
import random
import pandas as pd

size = 20 # Nb boats
rounds = 10 # nb of time steps

boat_ids = range(size)
boat_speeds = [random.randint(0,15) for i in range(size)]
ports = ['BREST', 'VALENCIA', 'PALERMO', 'BRIGHTON', 'AMSTERDAM', 'STOCKHOLM', 'CORK']
ports_list = [random.choice(ports) for i in range(size)]
boats_data_init = {
    'ID': boat_ids,
    'Speed': boat_speeds,
    'Destination': ports_list
}

df_boats_step0 = pd.DataFrame(boats_data_init)

In [2]:

def evolve(boat_df):
    random.seed()
    boat_speeds_updated = [max(0, boat_df['Speed'][i]+random.randint(-3,3)) for i in range(size)]
    new_boat_df = {
        'ID': boat_df['ID'],
        'Speed': boat_speeds_updated,
        'Destination': boat_df['Destination']
    }
    return(new_boat_df)

dfs = []
dfs.append(df_boats_step0)

df_boat_next = df_boats_step0
for i in range(rounds):
    df_boats_next = pd.DataFrame(evolve(df_boat_next))
    dfs.append(df_boats_next)

In [3]:
dfs[0]

    ID  Speed Destination
0    0      8       BREST
1    1      9    VALENCIA
2    2     15    BRIGHTON
3    3      5   STOCKHOLM
4    4      7        CORK
5    5      9        CORK
6    6      1     PALERMO
7    7      2   STOCKHOLM
8    8      5   STOCKHOLM
9    9      9     PALERMO
10  10      9       BREST
11  11      9       BREST
12  12     11   AMSTERDAM
13  13      5   AMSTERDAM
14  14      5       BREST
15  15      7    BRIGHTON
16  16      8     PALERMO
17  17     12    VALENCIA
18  18      1     PALERMO
19  19     10     PALERMO

In [4]:
dfs[1]

    ID  Speed Destination
0    0     10       BREST
1    1     11    VALENCIA
2    2     17    BRIGHTON
3    3      2   STOCKHOLM
4    4     10        CORK
5    5      7        CORK
6    6      1     PALERMO
7    7      5   STOCKHOLM
8    8      2   STOCKHOLM
9    9      7     PALERMO
10  10     12       BREST
11  11     11       BREST
12  12     11   AMSTERDAM
13  13      5   AMSTERDAM
14  14      3       BREST
15  15      4    BRIGHTON
16  16      8     PALERMO
17  17     15    VALENCIA
18  18      2     PALERMO
19  19      7     PALERMO

In [5]:
for i in range(rounds):
    filename = 'boats_small'+str(i)+'.csv'
    dfs[i].to_csv(filename)